# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo
  pod 'RxCocoa', '5.1.1', :source => 'https://cdn.cocoapods.org/'
  pod 'RxSwift', '5.1.1', :source => 'https://cdn.cocoapods.org/'

	
	# Pods for DouYu_Project

 pod "Kingfisher"
 pod "SnapKit"
 pod "R.swift"
#pod 'Alamofire'
pod 'Alamofire', '~> 5.0'

pod 'HandyJSON'
pod 'SwiftyJSON'

end
